import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
    gettingStartedSidebar: ["gettingStarted/index"],
    nodesSidebar: [
        "nodes/intro",
        {
            type: "category",
            label: "Spawn nodes",
            items: ["nodes/spawn/constantSpawn", "nodes/spawn/burstSpawn"],
        },
        {
            type: "category",
            label: "Initialize nodes",
            items: [
                "nodes/initialize/addPosition",
                "nodes/initialize/addPositionFromShape",
                "nodes/initialize/setColor",
                "nodes/initialize/setEmission",
                "nodes/initialize/setLifetime",
                "nodes/initialize/setLifetimeRandom",
                "nodes/initialize/setPosition",
                "nodes/initialize/setPositionToParent",
                "nodes/initialize/setRotationXYZ",
                "nodes/initialize/setRotationZ",
                "nodes/initialize/setRotationZRandom",
                "nodes/initialize/setSize",
                "nodes/initialize/setSizeRandom",
                "nodes/initialize/setSizeXYZ",
                "nodes/initialize/setTransparency",
                "nodes/initialize/setVelocity",
                "nodes/initialize/setVelocityRandom",
            ],
        },
        {
            type: "category",
            label: "Update nodes",
            items: [
                "nodes/update/accelerate",
                "nodes/update/addRotationXYZ",
                "nodes/update/addRotationXYZRandom",
                "nodes/update/addRotationZ",
                "nodes/update/addRotationZRandom",
                "nodes/update/addVelocity",
                "nodes/update/drag",
                "nodes/update/multiplySizeOverLife",
                "nodes/update/multiplyVelocityOverLife",
                "nodes/update/setColorOverLife",
                "nodes/update/setSizeOverLife",
                "nodes/update/setTransparencyOverLife",
            ],
        },
        {
            type: "category",
            label: "Render nodes",
            items: [
                "nodes/render/meshParticle",
                "nodes/render/planeParticle",
                "nodes/render/volumetricParticle",
            ],
        },
        {
            type: "category",
            label: "Logic nodes",
            items: [
                "nodes/logic/add",
                "nodes/logic/alivetime",
                "nodes/logic/clamp",
                "nodes/logic/cos",
                "nodes/logic/divide",
                "nodes/logic/multiply",
                "nodes/logic/numberOut",
                "nodes/logic/randomNumber",
                "nodes/logic/remap",
                "nodes/logic/sin",
                "nodes/logic/subtract",
                "nodes/logic/tan",
                "nodes/logic/time",
            ],
        },
    ],
    plannedFeaturesSidebar: [
        "plannedFeatures/index",
        {
            type: "category",
            label: "Higher Priority",
            items: [
                "plannedFeatures/higherPriority/index",
                "plannedFeatures/higherPriority/actions",
                "plannedFeatures/higherPriority/customVariables",
                "plannedFeatures/higherPriority/differentVelocityChangers",
                "plannedFeatures/higherPriority/physics",
            ],
        },
        {
            type: "category",
            label: "Lower Priority",
            items: [
                "plannedFeatures/lowerPriority/index",
                "plannedFeatures/lowerPriority/beams",
                "plannedFeatures/lowerPriority/delays",
                "plannedFeatures/lowerPriority/editableMeshEditableImage",
                "plannedFeatures/lowerPriority/groupings",
                "plannedFeatures/lowerPriority/groupSelection",
                "plannedFeatures/lowerPriority/imageBrowser",
                "plannedFeatures/lowerPriority/miniSystems",
                "plannedFeatures/lowerPriority/optimization",
                "plannedFeatures/lowerPriority/qol",
                "plannedFeatures/lowerPriority/redesignUI",
                "plannedFeatures/lowerPriority/splitSystemGroups",
                "plannedFeatures/lowerPriority/undoSupport",
            ],
        },
    ],
};

export default sidebars;
